server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: file-storing-service
          uri: http://localhost:5001
          predicates:
            - Path=/files/**
        - id: file-analysis-service
          uri: http://localhost:5002
          predicates:
            - Path=/analysis/**
        # Маршруты для API-документации
        - id: file-storing-swagger-ui
          uri: http://localhost:5001
          predicates:
            - Path=/file-storing/swagger-ui/**
          filters:
            - RewritePath=/file-storing/swagger-ui/(?<segment>.*), /swagger-ui/$\{segment}
        - id: file-storing-api-docs
          uri: http://localhost:5001
          predicates:
            - Path=/file-storing/v3/api-docs/**
          filters:
            - RewritePath=/file-storing/v3/api-docs/(?<segment>.*), /v3/api-docs/$\{segment}
        - id: file-analysis-swagger-ui
          uri: http://localhost:5002
          predicates:
            - Path=/file-analysis/swagger-ui/**
          filters:
            - RewritePath=/file-analysis/swagger-ui/(?<segment>.*), /swagger-ui/$\{segment}
        - id: file-analysis-api-docs
          uri: http://localhost:5002
          predicates:
            - Path=/file-analysis/v3/api-docs/**
          filters:
            - RewritePath=/file-analysis/v3/api-docs/(?<segment>.*), /v3/api-docs/$\{segment}
  main:
    web-application-type: reactive

# Настройки SpringDoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /file-storing/v3/api-docs
        name: File Storing Service
      - url: /file-analysis/v3/api-docs
        name: File Analysis Service
  api-docs:
    path: /v3/api-docs
    enabled: true