server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: file-storing-service
          uri: http://localhost:5001
          predicates:
            - Path=/files/**
        - id: file-analysis-service
          uri: http://localhost:5002
          predicates:
            - Path=/analysis/**
  main:
    web-application-type: reactive

# Настройки SpringDoc
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true