server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: file-storing-service
          uri: http://localhost:5001
          predicates:
            - Path=/files/**
        - id: file-analysis-service
          uri: http://localhost:5002
          predicates:
            - Path=/analysis/**
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html