server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: file-storing-service
          uri: http://localhost:5001
          predicates:
            - Path=/files/**
        - id: file-analysis-service
          uri: http://localhost:5002
          predicates:
            - Path=/analysis/**
      # Отключаем автоматическую маршрутизацию для корневого пути,
      # чтобы обрабатывать его нашим контроллером
      default-filters:
        - name: RouteToRequestUrl
          args:
            enabled: false
  main:
    web-application-type: reactive

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html